(() => {
  "use strict";

  const languages = {
    en: ["English", "en-US", "ltr"], "zh-Hans": ["简体中文", "zh-CN", "ltr"], "zh-Hant": ["繁體中文", "zh-TW", "ltr"],
    es: ["Español", "es-ES", "ltr"], ja: ["日本語", "ja-JP", "ltr"], ko: ["한국어", "ko-KR", "ltr"], fr: ["Français", "fr-FR", "ltr"],
    de: ["Deutsch", "de-DE", "ltr"], "pt-BR": ["Português", "pt-BR", "ltr"], ar: ["العربية", "ar", "rtl"]
  };

  const en = {
    navHow:"How it works",navPrivacy:"Privacy",navSupport:"Support",heroTitle:"Lock your distractions.<br>Keep the essentials.",heroBody:"Locking Phone automatically blocks distracting apps at bedtime and restores them in the morning.",download:"Coming soon on the App Store",howLink:"How it works",previewLabel:"Nightly Lock",previewEvery:"Every day",previewStart:"Start",previewEnd:"Restore",previewActive:"Plan active",previewHint:"Locks automatically tonight",previewAllowed:"Essentials stay available",phone:"Phone",messages:"Messages",alarm:"Alarm",feature1Title:"Automatic nightly lock",feature1Body:"Starts and restores on your chosen schedule.",feature2Title:"Essentials stay available",feature2Body:"Phone, Messages, and Alarm follow iOS Always Allowed.",feature3Title:"No temporary bypass",feature3Body:"Once your night begins, there is no shortcut inside the app.",feature4Title:"Seven-night report",feature4Body:"Review completed nights and optional morning check-ins.",howTitle:"Set it once. Sleep without negotiating.",step1Title:"Choose your hours",step1Body:"Pick bedtime and morning restore time.",step2Title:"Allow Screen Time",step2Body:"Grant Apple’s permission once.",step3Title:"Wake up restored",step3Body:"Your apps return automatically in the morning.",privacyTitle:"Your routine stays on your device.",privacyBody:"No account, no ads, no analytics SDK, and no developer server. Your schedule and reports stay local.",privacyLink:"Read the privacy policy",ctaTitle:"Let bedtime make the decision.",ctaBody:"Set your nightly boundary once, then let iOS keep it."
  };

  const translations = {
    en,
    "zh-Hans": {...en,navHow:"使用方式",navPrivacy:"隐私",navSupport:"支持",heroTitle:"锁住干扰。<br>保留必要功能。",heroBody:"Locking Phone 在睡前自动限制让你分心的 App，并在早晨按时恢复。",download:"即将上线 App Store",howLink:"了解使用方式",previewLabel:"夜间锁机",previewEvery:"每天",previewStart:"开始",previewEnd:"恢复",previewActive:"计划已启用",previewHint:"今晚将自动开始",previewAllowed:"必要功能保持可用",phone:"电话",messages:"信息",alarm:"闹钟",feature1Title:"夜间自动锁机",feature1Body:"按你设定的时间自动开始和恢复。",feature2Title:"保留必要功能",feature2Body:"电话、信息和闹钟遵循 iOS“始终允许”设置。",feature3Title:"不允许临时放行",feature3Body:"夜间计划开始后，App 内没有临时解锁捷径。",feature4Title:"七晚隔离报告",feature4Body:"回顾完成的夜晚和可选的早晨自评。",howTitle:"只设置一次，不再和自己讨价还价。",step1Title:"选择时间",step1Body:"设定睡觉和早晨恢复时间。",step2Title:"允许屏幕使用时间",step2Body:"只需完成一次 Apple 系统授权。",step3Title:"早晨自动恢复",step3Body:"你的 App 会在早晨按时恢复。",privacyTitle:"你的记录，只留在你的设备上。",privacyBody:"没有账号、广告、分析 SDK 或开发者服务器。计划和报告保存在本机。",privacyLink:"阅读隐私政策",ctaTitle:"让睡觉时间替你做决定。",ctaBody:"设置一次夜间边界，之后交给 iOS 执行。"},
    "zh-Hant": {...en,navHow:"使用方式",navPrivacy:"隱私",navSupport:"支援",heroTitle:"鎖住干擾。<br>保留必要功能。",heroBody:"Locking Phone 在睡前自動限制令人分心的 App，並於早晨按時恢復。",download:"即將上架 App Store",howLink:"了解使用方式",previewLabel:"夜間鎖機",previewEvery:"每天",previewStart:"開始",previewEnd:"恢復",previewActive:"計畫已啟用",previewHint:"今晚將自動開始",previewAllowed:"必要功能保持可用",phone:"電話",messages:"訊息",alarm:"鬧鐘",feature1Title:"夜間自動鎖機",feature1Body:"依你設定的時間自動開始與恢復。",feature2Title:"保留必要功能",feature2Body:"電話、訊息與鬧鐘依照 iOS「永遠允許」設定。",feature3Title:"不允許暫時放行",feature3Body:"夜間計畫開始後，App 內沒有暫時解鎖捷徑。",feature4Title:"七晚隔離報告",feature4Body:"回顧完成的夜晚與可選的早晨自評。",howTitle:"只設定一次，不再和自己討價還價。",step1Title:"選擇時間",step1Body:"設定睡覺與早晨恢復時間。",step2Title:"允許螢幕使用時間",step2Body:"只需完成一次 Apple 系統授權。",step3Title:"早晨自動恢復",step3Body:"你的 App 會在早晨按時恢復。",privacyTitle:"你的記錄，只留在你的裝置上。",privacyBody:"沒有帳號、廣告、分析 SDK 或開發者伺服器。計畫與報告保存在本機。",privacyLink:"閱讀隱私權政策",ctaTitle:"讓睡覺時間替你做決定。",ctaBody:"設定一次夜間界線，之後交給 iOS 執行。"},
    es: {...en,navHow:"Cómo funciona",navPrivacy:"Privacidad",navSupport:"Soporte",heroTitle:"Bloquea las distracciones.<br>Conserva lo esencial.",heroBody:"Locking Phone bloquea automáticamente las apps que distraen al acostarte y las restaura por la mañana.",download:"Próximamente en App Store",howLink:"Cómo funciona",feature1Title:"Bloqueo nocturno automático",feature1Body:"Comienza y termina según tu horario.",feature2Title:"Lo esencial sigue disponible",feature2Body:"Teléfono, Mensajes y Alarma siguen Siempre permitido de iOS.",feature3Title:"Sin desbloqueo temporal",feature3Body:"Cuando empieza la noche, no hay atajos dentro de la app.",feature4Title:"Informe de siete noches",feature4Body:"Revisa las noches completadas y los registros matinales opcionales.",howTitle:"Configúralo una vez. Duerme sin negociar.",step1Title:"Elige tu horario",step1Body:"Define la hora de dormir y de restauración.",step2Title:"Autoriza Tiempo de uso",step2Body:"Concede una vez el permiso de Apple.",step3Title:"Despierta con todo restaurado",step3Body:"Tus apps regresan automáticamente.",privacyTitle:"Tu rutina permanece en tu dispositivo.",privacyBody:"Sin cuenta, anuncios, SDK de análisis ni servidor del desarrollador.",privacyLink:"Leer la política de privacidad",ctaTitle:"Deja que la hora de dormir decida.",ctaBody:"Define el límite una vez y deja que iOS lo cumpla."},
    ja: {...en,navHow:"使い方",navPrivacy:"プライバシー",navSupport:"サポート",heroTitle:"気が散るアプリをロック。<br>必要な機能はそのまま。",heroBody:"Locking Phoneは就寝時に気が散るアプリを自動制限し、朝に復元します。",download:"App Storeで近日公開",howLink:"使い方を見る",feature1Title:"夜間の自動ロック",feature1Body:"選んだ時刻に開始し、朝に復元します。",feature2Title:"必要な機能は利用可能",feature2Body:"電話、メッセージ、アラームはiOSの常に許可に従います。",feature3Title:"一時解除なし",feature3Body:"開始後、App内に一時解除の近道はありません。",feature4Title:"7夜レポート",feature4Body:"完了した夜と任意の朝の記録を確認できます。",howTitle:"一度設定して、迷わず眠る。",step1Title:"時間を選ぶ",step1Body:"就寝時刻と朝の復元時刻を設定。",step2Title:"スクリーンタイムを許可",step2Body:"Appleの権限を一度だけ許可。",step3Title:"朝に自動復元",step3Body:"朝になるとアプリが戻ります。",privacyTitle:"記録は端末内に残ります。",privacyBody:"アカウント、広告、分析SDK、開発者サーバーはありません。",privacyLink:"プライバシーポリシー",ctaTitle:"就寝時間に判断を任せよう。",ctaBody:"夜の境界を一度設定し、あとはiOSに任せます。"},
    ko: {...en,navHow:"사용 방법",navPrivacy:"개인정보",navSupport:"지원",heroTitle:"방해 요소는 잠그고.<br>필수 기능은 그대로.",heroBody:"Locking Phone은 취침 시간에 방해되는 앱을 자동 차단하고 아침에 복원합니다.",download:"App Store 출시 예정",howLink:"사용 방법",feature1Title:"자동 야간 잠금",feature1Body:"선택한 일정에 맞춰 시작하고 복원합니다.",feature2Title:"필수 기능 유지",feature2Body:"전화, 메시지, 알람은 iOS 항상 허용 설정을 따릅니다.",feature3Title:"임시 해제 없음",feature3Body:"야간 계획이 시작되면 앱 안에 우회 방법이 없습니다.",feature4Title:"7일 밤 보고서",feature4Body:"완료한 밤과 선택적 아침 기록을 확인합니다.",howTitle:"한 번 설정하고, 고민 없이 잠드세요.",step1Title:"시간 선택",step1Body:"취침 및 아침 복원 시간을 정하세요.",step2Title:"스크린 타임 허용",step2Body:"Apple 권한을 한 번 허용하세요.",step3Title:"아침 자동 복원",step3Body:"아침에 앱이 자동으로 돌아옵니다.",privacyTitle:"기록은 기기에만 남습니다.",privacyBody:"계정, 광고, 분석 SDK, 개발자 서버가 없습니다.",privacyLink:"개인정보 처리방침",ctaTitle:"취침 시간이 결정하게 하세요.",ctaBody:"야간 경계를 한 번 정하고 iOS에 맡기세요."},
    fr: {...en,navHow:"Fonctionnement",navPrivacy:"Confidentialité",navSupport:"Assistance",heroTitle:"Bloquez les distractions.<br>Gardez l’essentiel.",heroBody:"Locking Phone bloque automatiquement les apps distrayantes au coucher et les restaure le matin.",download:"Bientôt sur l’App Store",howLink:"Fonctionnement",feature1Title:"Blocage nocturne automatique",feature1Body:"Démarre et se termine selon vos horaires.",feature2Title:"L’essentiel reste disponible",feature2Body:"Téléphone, Messages et Alarme suivent Toujours autorisées d’iOS.",feature3Title:"Aucun déblocage temporaire",feature3Body:"Une fois la nuit commencée, aucun raccourci dans l’app.",feature4Title:"Rapport sur sept nuits",feature4Body:"Consultez les nuits terminées et bilans matinaux facultatifs.",howTitle:"Réglez une fois. Dormez sans négocier.",step1Title:"Choisissez vos heures",step1Body:"Définissez le coucher et le réveil.",step2Title:"Autorisez Temps d’écran",step2Body:"Accordez une fois l’autorisation Apple.",step3Title:"Réveil restauré",step3Body:"Vos apps reviennent automatiquement le matin.",privacyTitle:"Votre routine reste sur votre appareil.",privacyBody:"Sans compte, publicité, SDK d’analyse ou serveur développeur.",privacyLink:"Lire la politique de confidentialité",ctaTitle:"Laissez l’heure du coucher décider.",ctaBody:"Définissez votre limite et laissez iOS la respecter."},
    de: {...en,navHow:"So funktioniert es",navPrivacy:"Datenschutz",navSupport:"Support",heroTitle:"Ablenkungen sperren.<br>Das Wesentliche behalten.",heroBody:"Locking Phone blockiert abends automatisch ablenkende Apps und stellt sie morgens wieder her.",download:"Bald im App Store",howLink:"So funktioniert es",feature1Title:"Automatische Nachtsperre",feature1Body:"Startet und endet nach deinem Zeitplan.",feature2Title:"Wichtiges bleibt verfügbar",feature2Body:"Telefon, Nachrichten und Wecker folgen Immer erlauben in iOS.",feature3Title:"Keine vorübergehende Freigabe",feature3Body:"Nach dem Start gibt es in der App keine Abkürzung.",feature4Title:"Sieben-Nächte-Bericht",feature4Body:"Abgeschlossene Nächte und optionale Morgenangaben ansehen.",howTitle:"Einmal einstellen. Ohne Verhandeln schlafen.",step1Title:"Zeiten wählen",step1Body:"Schlafens- und Wiederherstellungszeit festlegen.",step2Title:"Bildschirmzeit erlauben",step2Body:"Apple-Berechtigung einmal erteilen.",step3Title:"Morgens wiederhergestellt",step3Body:"Deine Apps kehren automatisch zurück.",privacyTitle:"Deine Routine bleibt auf deinem Gerät.",privacyBody:"Kein Konto, keine Werbung, kein Analyse-SDK, kein Entwicklerserver.",privacyLink:"Datenschutzerklärung lesen",ctaTitle:"Lass die Schlafenszeit entscheiden.",ctaBody:"Grenze einmal festlegen und von iOS einhalten lassen."},
    "pt-BR": {...en,navHow:"Como funciona",navPrivacy:"Privacidade",navSupport:"Suporte",heroTitle:"Bloqueie as distrações.<br>Mantenha o essencial.",heroBody:"O Locking Phone bloqueia automaticamente apps que distraem na hora de dormir e os restaura pela manhã.",download:"Em breve na App Store",howLink:"Como funciona",feature1Title:"Bloqueio noturno automático",feature1Body:"Começa e termina no horário escolhido.",feature2Title:"O essencial continua disponível",feature2Body:"Telefone, Mensagens e Alarme seguem Sempre Permitido do iOS.",feature3Title:"Sem liberação temporária",feature3Body:"Depois que a noite começa, não há atalho dentro do app.",feature4Title:"Relatório de sete noites",feature4Body:"Veja noites concluídas e check-ins matinais opcionais.",howTitle:"Configure uma vez. Durma sem negociar.",step1Title:"Escolha os horários",step1Body:"Defina o horário de dormir e restaurar.",step2Title:"Permita Tempo de Uso",step2Body:"Conceda a permissão da Apple uma vez.",step3Title:"Acorde com tudo restaurado",step3Body:"Seus apps voltam automaticamente pela manhã.",privacyTitle:"Sua rotina fica no seu dispositivo.",privacyBody:"Sem conta, anúncios, SDK de análise ou servidor do desenvolvedor.",privacyLink:"Ler a política de privacidade",ctaTitle:"Deixe a hora de dormir decidir.",ctaBody:"Defina o limite uma vez e deixe o iOS mantê-lo."},
    ar: {...en,navHow:"طريقة العمل",navPrivacy:"الخصوصية",navSupport:"الدعم",heroTitle:"اقفل المشتتات.<br>وأبقِ الأساسيات.",heroBody:"يقفل Locking Phone التطبيقات المشتتة تلقائيًا عند النوم ويعيدها في الصباح.",download:"قريبًا على App Store",howLink:"طريقة العمل",previewLabel:"القفل الليلي",previewEvery:"كل يوم",previewStart:"البدء",previewEnd:"الاستعادة",previewActive:"الخطة مفعلة",previewHint:"سيبدأ القفل تلقائيًا الليلة",previewAllowed:"الأساسيات تبقى متاحة",phone:"الهاتف",messages:"الرسائل",alarm:"المنبه",feature1Title:"قفل ليلي تلقائي",feature1Body:"يبدأ وينتهي حسب الجدول الذي تختاره.",feature2Title:"الأساسيات تبقى متاحة",feature2Body:"يتبع الهاتف والرسائل والمنبه إعدادات مسموح دائمًا في iOS.",feature3Title:"لا فتح مؤقت",feature3Body:"بعد بدء الليل لا يوجد اختصار للفتح داخل التطبيق.",feature4Title:"تقرير سبع ليالٍ",feature4Body:"راجع الليالي المكتملة وتسجيلات الصباح الاختيارية.",howTitle:"اضبطه مرة واحدة. ونَم بلا مساومة.",step1Title:"اختر الساعات",step1Body:"حدد وقت النوم والاستعادة صباحًا.",step2Title:"اسمح بمدة استخدام الجهاز",step2Body:"امنح إذن Apple مرة واحدة.",step3Title:"استيقظ مع الاستعادة",step3Body:"تعود تطبيقاتك تلقائيًا في الصباح.",privacyTitle:"يبقى روتينك على جهازك.",privacyBody:"لا حساب ولا إعلانات ولا تحليلات ولا خادم للمطور.",privacyLink:"اقرأ سياسة الخصوصية",ctaTitle:"دع وقت النوم يتخذ القرار.",ctaBody:"اضبط حدودك الليلية مرة واترك iOS يحافظ عليها."}
  };

  const aliases = {"zh-CN":"zh-Hans","zh-SG":"zh-Hans",zh:"zh-Hans","zh-TW":"zh-Hant","zh-HK":"zh-Hant","zh-MO":"zh-Hant",pt:"pt-BR","pt-BR":"pt-BR"};
  function resolveLanguage() {
    const requested = new URLSearchParams(location.search).get("lang");
    if (translations[requested]) return requested;
    const saved = localStorage.getItem("lockingPhoneLanguage");
    if (translations[saved]) return saved;
    for (const candidate of navigator.languages || [navigator.language]) {
      if (aliases[candidate]) return aliases[candidate];
      const base = candidate.split("-")[0]; if (translations[base]) return base;
    }
    return "en";
  }
  function render(code) {
    const copy = translations[code]; const meta = languages[code];
    document.documentElement.lang = meta[1]; document.documentElement.dir = meta[2];
    document.querySelectorAll("[data-home-copy]").forEach((element) => { const value = copy[element.dataset.homeCopy]; if (value) element.innerHTML = value; });
    document.querySelectorAll("a[href$='privacy.html'], a[href$='support.html']").forEach((link) => { const url = new URL(link.href); url.searchParams.set("lang", code); link.href = url; });
    document.getElementById("languageSelect").value = code;
  }
  const select = document.getElementById("languageSelect");
  select.innerHTML = Object.entries(languages).map(([code, meta]) => `<option value="${code}">${meta[0]}</option>`).join("");
  select.addEventListener("change", (event) => { const code = event.target.value; localStorage.setItem("lockingPhoneLanguage", code); const url = new URL(location.href); url.searchParams.set("lang", code); history.replaceState(null, "", url); render(code); });
  document.getElementById("copyrightYear").textContent = new Date().getFullYear();
  render(resolveLanguage());
})();
